id: AD709ED78
title: Concise Offering of the Body from the Root Text of the Heart Accomplishment
  of the Guru Tukdrup, The Essential Manual of Oral Instructions (Shaldam Nyingjang)
type: translation
pechas:
- I59826BC2
- I00C40341
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:35:55.385006
  last_modified_at: 2023-01-04 11:35:55.385010
  collections:
  - Dilgo Khyentse Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I59826BC2/DEA5: 53B2
  I00C40341/9310: 53B2
